name: Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v3
      with:
        version: 8
    - uses: actions/setup-node@v3
      with:
        node-version: lts
        cache: 'pnpm'
    - run: pnpm
    - run: pnpm run --if-present build
    - run: pnpm test
